import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :pantry, PantryWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  url: [host: "pantry.relar.dev"],
  check_origin: ["//pantry.relar.dev"]

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :pantry, Pantry.Mailer,
  adapter: Swoosh.Adapters.Mailgun,
  base_url: "https://api.eu.mailgun.net/v3",
  api_key: System.get_env("MAILGUN_API_KEY"),
  domain: System.get_env("MAILGUN_DOMAIN")

config :swoosh, :api_client, Swoosh.ApiClient.Req
